# syntax=docker/dockerfile:1

ARG GO_VERSION=1.23.3

FROM golang:${GO_VERSION}-alpine

WORKDIR /src
ENV CGO_ENABLED=0
ENV GOTOOLCHAIN=local
ENV GOCACHE=/tmp/go-build

COPY go.mod go.sum ./
RUN go mod download

COPY internal ./internal
COPY tests ./tests

RUN addgroup -g 10001 -S tester && \
    adduser -u 10001 -S -G tester tester

USER tester:tester
ENTRYPOINT ["go", "test", "-mod=readonly", "-tags=e2e", "-count=1", "-v", "./tests/e2e"]
